##### Buzzard v2.0 imput files
## copacabana master files
members_infile   : /data/des61.a/data/johnny/DESY3/data/cutouts/y3_gold_2.2.1_wide_sofcol_run_redmapper_v6.4.22_wv1.2_full_hpx8_{:05d}.hdf5
cluster_infile   : /data/des61.a/data/johnny/DESY3/data/cutouts/y3_gold_2.2.1_wide_sofcol_run_redmapper_v6.4.22_wv1.2_full.fits
master_outfile   : /data/des61.a/data/johnny/DESY3/data/output/y3_gold_2.2.1_wide_sofcol_run_redmapper_v6.4.22_wv1.2_full_copa_v2.1_{:05d}.hdf5
columns_yaml_file: /data/des61.a/data/johnny/DESY3/projects/CopacabanaRuns/analysis/aux_files/columns_desy3_rm.yaml
pixelmap_file    : 


######## copa setup #######
zmin_gal: 0.0
zmax_gal: 1.5
dz_max  : 0.3

## radial cuts
rmax : 3.
r_in : 4.
r_out: 6.

## pz0 factor
pz_factor: 0.835

## relative mag cut; dmag_lim only works if mag_selection is empty
mag_model_file: /home/s1/jesteves/git/ccopa/aux_files/annis_mags_04_Lcut.txt
mag_selection : 02Lstar
dmag_lim: 2

## cluster aperture radii, it can be a number in Mpc, values: rhod/r200 (simulation)
r_aper_model : rhod
r_aper_value : 

## parallel process
copa_number_of_chunks: 100

## Photo-z setup
# 1st model: a gaussian distribution centered on zcls with a std of z_window
# 2nd model: a gaussian distribution centered on zcls+bias with a std dependeding on redshift
# 2nd model is a text file with: z, bias, std
z_window     : 0.03
z_model_file : /data/des61.a/data/johnny/DESY3/projects/CopacabanaRuns/analysis/aux_files/modelDNF_correction_z_gold_2_2.txt

## Healpixel config
healpixel_setup : True
# healpixel_list  : [262, 727, 752]
healpixel_list  : [543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 608, 610]
## for the whole sample use the pixel list below


######## bma setup #######
## paralell
bma_number_of_chunks: 650

## stellar population libray file
lib_inPath: /data/des61.a/data/pbarchi/galaxyClusters/simha_miles_Nov2016/
